version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: bookmynanny-client:latest  
   

  bookmynanny:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4001:5173"
    depends_on:
      - server
    image: bookmynanny-server:latest