version: '3'

services:
  bookmynanny:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4001:5173"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4002:3000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
